package com.gimbal.logger;

public enum GimbalStatus {
    
    SUCCESS("SYSTEM_STATUS_SUCCESS"),
    FAILURE("SYSTEM_STATUS_FAILED"),
    ERROR_INVALID_COMMAND("INVALID_COMMAND"),
    MISSING_COMMAND("PARTIAL_COMMAND_FOUND"),
    INVALID_TOOL("TOOL_NAME_NOT_FOUND"),
    FLAG_NOT_SUPPORTED("FLAG_NOT_SUPPORTED"),
    PROVIDE_HELP("PROVIDE_COMMAND_HELP"),
    PROVIDE_VERSION("PROVIDE_SYSTEM_VERSION"),

    INSTALL_STARTED("INSTALLATION_INITIALIZED"),
    INSTALL_COMPLETED("INSTALL_DONE_SYSTEM_SUCCESS"),
    INSTALL_FAILED("INSTALL_FAILED_SYSTEM_EXITED"),

    INSTALL_JAVA("INSTALLING_JAVA_INITIALIZED"),
    INSTALL_MAVEN("INSTALLING_MAVEN_INITIALIZED"),
    INSTALL_GIT("INSTALLING_GIT_INITIALIZED"),

    SYSTEM_INITIALIZED("SYSTEM_IS_READY"),
    SYSTEM_RUNNING("GIMBAL_IS_ALIVE"),

    NETWORK_ERROR("NETWORK_ERROR_FOUND"),
    PERMISSION_DENIED("PERMISSION_DENIED_SYSTEM_EXIT"),
    UNKNOWN_ERROR("SOMETHING_WENT_WRONG");

    private final String message;

    GimbalStatus(String message){
        this.message = message;
    }

    public String getMessage(){
        return this.message;
    }
}
